### ISSUE TITLE
Drop-in replacement for msgpack-numpy?

### ISSUE THREAD

**Issue by jacopoabramo** [clearviewai/msgpack-numpy-rs#1]
Hello, I have a question concerning the usage of msgpack-numpy-rs.

Can this be used in replacement to it's sister project msgpack-numpy? The project mentioned the following:

> [msgpack-numpy-rs](https://github.com/clearviewai/msgpack-numpy-rs) by [Terrence Liu](https://github.com/terencezl) is a Rust crate (mostly) compatible with msgpack-numpy that can serialize and deserialize numpy arrays with msgpack.

I was curious of what that "mostly" means. Furthermore, I'm currently writing a Python application that interacts with different devices that can acquire data as numpy arrays and I'm setting up a messaging system which can send these arrays accross different in-process endpoints. Since the application is in Python, I'm wondering if I should just stick to msgpack-numpy since this repository seems to be compatible only with Rust projects but I would like to benefit the extra speed if possible.

**Comment by terencezl** [comment]
Hi @jacopoabramo . This is not supposed to be a replacement for Python uses, but rather a counterpart in Rust. It enables you to cross-communicate between Python and Rust in msgpack-numpy format outlined by the original `msgpack-numpy` Python repo.

"mostly" means in the Overview section:

* It supports `bool`, `u8`, `i8`, `u16`, `i16`, `f16` (through the [`half`](https://crates.io/crates/half) crate), `u32`, `i32`, `f32`, `u64`, `i64`, `f64`.
* No support for arrays with complex numbers (`'c'`), byte strings (`'S'`), unicode strings (`'U'`), or other non-primitive types as elements. No support for structured/tuple data types (`'V'`), or object-type data that need pickling (`'O'`) ([ref](https://github.com/lebedov/msgpack-numpy/blob/0.4.8/msgpack_numpy.py)).

Speed-wise, if you are sending/de/serializing large enough sized arrays, the original Python implementation actually mostly calls into C by numpy and msgpack itself. So you are already getting very good speed. If you are sending small arrays, then Python itself is the issue for slowness, you would have to switch language to get that lifted off.

**Comment by jacopoabramo** [comment]
Thanks for the explanation, closing.
